const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Service to generate PDF reports
 */
class ReportService {
    /**
     * Generate a monthly summary PDF
     * @param {Object} data - { user, month, year, transactions, stats }
     * @returns {Promise<Buffer>}
     */
    async generateMonthlyReport(data) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                let buffers = [];
                doc.on('data', buffers.push.bind(buffers));
                doc.on('end', () => {
                    let pdfData = Buffer.concat(buffers);
                    resolve(pdfData);
                });

                // Header
                doc.fillColor('#444444')
                    .fontSize(20)
                    .text('DollarDairy Financial Report', 110, 57)
                    .fontSize(10)
                    .text('Date:', 200, 65, { align: 'right' })
                    .text(`${data.month} ${data.year}`, 200, 80, { align: 'right' })
                    .moveDown();

                // Horizontal Line
                doc.moveTo(50, 100).lineTo(550, 100).stroke();

                // User Info
                doc.fontSize(12)
                    .text(`Name: ${data.user.firstName || ''} ${data.user.lastName || ''}`, 50, 115)
                    .moveDown();

                // Summary Stats
                doc.fontSize(14).text('Monthly Summary', 50, 140);
                doc.fontSize(10)
                    .text(`Total Income: $${data.stats.income.toFixed(2)}`, 60, 160)
                    .text(`Total Expenses: $${data.stats.expenses.toFixed(2)}`, 60, 175)
                    .text(`Net Balance: $${(data.stats.income - data.stats.expenses).toFixed(2)}`, 60, 190);

                // Transactions Table
                doc.moveDown(2);
                doc.fontSize(14).text('Transaction History', 50, 220);

                let currentY = 245;
                // Table Header
                doc.fontSize(10).text('Date', 50, currentY, { bold: true });
                doc.text('Title', 120, currentY, { bold: true });
                doc.text('Category', 300, currentY, { bold: true });
                doc.text('Amount', 480, currentY, { align: 'right', bold: true });

                currentY += 15;
                doc.moveTo(50, currentY).lineTo(550, currentY).stroke();
                currentY += 10;

                data.transactions.forEach((tx, index) => {
                    if (currentY > 700) {
                        doc.addPage();
                        currentY = 50;
                    }

                    const date = new Date(tx.date).toLocaleDateString();
                    doc.fontSize(9).text(date, 50, currentY);
                    doc.text(tx.title.substring(0, 30), 120, currentY);
                    doc.text(tx.categoryName || 'General', 300, currentY);

                    const amountText = (tx.type === 'expense' ? '-$' : '+$') + parseFloat(tx.amount).toFixed(2);
                    doc.fillColor(tx.type === 'expense' ? '#EF4444' : '#10B981')
                        .text(amountText, 480, currentY, { align: 'right' })
                        .fillColor('#444444');

                    currentY += 20;
                });

                // Footer
                doc.fontSize(8)
                    .text('Generated by DollarDairy - Your Personal Wealth Partner', 50, 750, { align: 'center', width: 500 });

                doc.end();
            } catch (err) {
                reject(err);
            }
        });
    }
}

module.exports = new ReportService();
